pub mod cli;
pub mod pxs;

/// Build-time information generated by the `built` crate.
#[allow(dead_code, clippy::doc_markdown)]
pub mod built_info {
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}
